export { default as LoginPage } from './login/components/Login'
export { default as RegisterPage } from './register/components/Register'
export { default as ForgotPasswordPage } from './forgot-password/components/forgot-password'
export { default as ResetPasswordPage } from './reset-password/components/reset-password'
export { Navbar } from './navbar'
export { default as AddProductForm } from './newProduct/components/new-product'
export { default as InventoryActivityLog } from './activity-log/components/InventoryActivityLog'
